### ISSUE TITLE
WAN verbinding

### ISSUE THREAD

**Issue by MartijnGuilliamsPXL** [12003586/PEM-3D-printer#21]

**Comment by GijsJackersPXL** [comment]
Er worden poorten opengezet op het elektronica netwerk.

**Comment by 12003586** [comment]
Er is een poort opengezet door Bart en octoprint kan via wan verbinding bereikt worden via:
http://octopi.pxl-ea-ict.be:24081/#temp

**Comment by GijsJackersPXL** [comment]
Gecontroleerd en werkt zoals het hoort.
