### ISSUE TITLE
Raspberry Pi met 3d-printer verbinden

### ISSUE THREAD

**Issue by GijsJackersPXL** [12003586/PEM-3D-printer#3]
[Raspberry Pi met 3d-printer verbinden.md](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Raspberry%20Pi%20met%203d-printer%20verbinden.md)

Sub tickets: 
- #6
- #7

**Comment by MartijnGuilliamsPXL** [comment]
[Raspberry Pi met 3d-printer verbinden.md](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Raspberry%20Pi%20met%203d-printer%20verbinden.md)

**Comment by MartijnGuilliamsPXL** [comment]
#6
