### ISSUE TITLE
Script gebruikers

### ISSUE THREAD

**Issue by MartijnGuilliamsPXL** [12003586/PEM-3D-printer#30]
Met dit script kan er voor elke leerling een User worden aangemaakt met een random wachtwoord die automatisch via mail wordt door gestuurd naar die leerling. Als elke leerling een eigen account heeft kan er via de logging van Octoprint gekeken worden welke gebruiker wat geprint heeft.

Deze epic is ook de samenvoeging van onderstaande scripts tot één script. De Gebruikers-verwijderen is natuurlijk wel een apart script.

[Documentatie](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Script%20gebruikers%20aanmaken.md)
[Code](https://github.com/12003586/PEM-3D-printer/blob/main/Code/Script-gebruikers/Script-gebruikers.py)

Sub tickets: 
- #39 
- #40
- #41
- #42
- #44
- #45

**Comment by GijsJackersPXL** [comment]
Allemaal gecontroleerd!
