### ISSUE TITLE
Gebruikers-aanmaken

### ISSUE THREAD

**Issue by MartijnGuilliamsPXL** [12003586/PEM-3D-printer#39]
Een script om een octoprint gebruiker aan te maken.

[Documentatie](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Script%20gebruikers%20aanmaken.md)
[Code](https://github.com/12003586/PEM-3D-printer/blob/main/Code/Script-gebruikers/gebruikers-aanmaken.py)

Epic: 
- #30

**Comment by GijsJackersPXL** [comment]
Deze code is getest geweest en er wordt een gebruiker aangemaakt.
