### ISSUE TITLE
Gebruikers-aanmaken-command-test

### ISSUE THREAD

**Issue by MartijnGuilliamsPXL** [12003586/PEM-3D-printer#40]
Een script om een http post command naar octoprint te testen.
In dit voorbeeld werd een reboot post gebruikt, omdat hier geen extra data meegestuurd moest worden.

[Documentatie](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Script%20gebruikers%20aanmaken.md)
[Code](https://github.com/12003586/PEM-3D-printer/blob/main/Code/Script-gebruikers/gebruikers-aanmaken-command-test.py)

Epic: 
- #30

**Comment by GijsJackersPXL** [comment]
Deze code is getest geweest en er wordt een gebruiker aangemaakt.
