### ISSUE TITLE
Gebruikers-aanmaken-csv

### ISSUE THREAD

**Issue by MartijnGuilliamsPXL** [12003586/PEM-3D-printer#44]
Een script om een csv bestand uit te lezen. Dit kan gebruikt worden om een csv lijst met mailadressen van leerlingen uit te lezen en voor elke leerling een account aan te maken.

[Documentatie](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Script%20gebruikers%20aanmaken.md)
[Code](https://github.com/12003586/PEM-3D-printer/blob/main/Code/Script-gebruikers/gebruikers-aanmaken-csv.py)

Epic: 
- #30

**Comment by GijsJackersPXL** [comment]
Deze code is getest geweest en de CSV lijst wordt ingelezen + een account wordt gemaakt.
