### ISSUE TITLE
Gebruikers-verwijderen

### ISSUE THREAD

**Issue by MartijnGuilliamsPXL** [12003586/PEM-3D-printer#45]
Een script om automatisch alle aangemaakte gebruikers uit een csv lijst weer te verwijderen van Octoprint.

[Documentatie](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Script%20gebruikers%20aanmaken.md)
[Code](https://github.com/12003586/PEM-3D-printer/blob/main/Code/Script-gebruikers/gebruikers-verwijderen.py)

Epic: 
- #30

**Comment by GijsJackersPXL** [comment]
Deze code is getest geweest en er worden gebruikers verwijderd die in de CSV lijst staan.
