### ISSUE TITLE
Bumper printen

### ISSUE THREAD

**Issue by 12003586** [12003586/PEM-3D-printer#5]

**Comment by GijsJackersPXL** [comment]
[Bumper.md](https://github.com/12003586/PEM-3D-printer/blob/main/Documentatie/Bumper.md)

**Comment by GijsJackersPXL** [comment]
Er moet een V2 van de bumper gemaakt worden.

**Comment by GijsJackersPXL** [comment]
Er moet een V3 van de bumper gemaakt worden.

**Comment by GijsJackersPXL** [comment]
BumperV3 is geprint en past over de extruder.

<img src="https://user-images.githubusercontent.com/56915241/203026522-ce7acc19-c63c-4654-8cc5-460a1106889b.jpg" alt="drawing" width="300"/>
